// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbdhgbebvjfdbsvsuemc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5iZGhnYmVidmpmZGJzdnN1ZW1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDM5MjksImV4cCI6MjA2NDExOTkyOX0.e5sIT2V0tJI4z8atMvPzACehMVErZC0kb5487AM-UIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);